---
driver_config:
  network:
  - ["forwarded_port", {guest: 4000, host: 4000}]

driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-13.10

suites:
  - name: default
    run_list:
      - recipe[strider-cd::default]
    attributes:
      strider-cd:
        users:
          'strider@example.com':
            password: password
            admin: true
