---
driver_config:
  network:
  - ["forwarded_port", {guest: 4000, host: 4000}]

driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-13.10

suites:
  - name: default
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    data_bag_path: "test/integration/default/data_bags"
    run_list:
      - recipe[strider::default]
    attributes:
      strider:
        users:
          'strider@example.com':
            password: password
            admin: true
